// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKddek_qIWldOB_Eef2YsNDq5K5wAq81I',
    appId: '1:643524386263:web:ca1d67e702745590c3ff92',
    messagingSenderId: '643524386263',
    projectId: 'memocards-37431',
    authDomain: 'memocards-37431.firebaseapp.com',
    storageBucket: 'memocards-37431.firebasestorage.app',
    measurementId: 'G-EMF8M5E193',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt40WVo9K1Y-QPR8iLcDgCh_ykmwbOU-E',
    appId: '1:643524386263:android:b649dcfcd8cde193c3ff92',
    messagingSenderId: '643524386263',
    projectId: 'memocards-37431',
    storageBucket: 'memocards-37431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyR1hGn-uEva54nPFJvz1KbDm1an7oGTk',
    appId: '1:643524386263:ios:6a64dec7510d605cc3ff92',
    messagingSenderId: '643524386263',
    projectId: 'memocards-37431',
    storageBucket: 'memocards-37431.firebasestorage.app',
    iosBundleId: 'com.example.flutterMemoCards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyR1hGn-uEva54nPFJvz1KbDm1an7oGTk',
    appId: '1:643524386263:ios:6a64dec7510d605cc3ff92',
    messagingSenderId: '643524386263',
    projectId: 'memocards-37431',
    storageBucket: 'memocards-37431.firebasestorage.app',
    iosBundleId: 'com.example.flutterMemoCards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKddek_qIWldOB_Eef2YsNDq5K5wAq81I',
    appId: '1:643524386263:web:87625263ac5c72d1c3ff92',
    messagingSenderId: '643524386263',
    projectId: 'memocards-37431',
    authDomain: 'memocards-37431.firebaseapp.com',
    storageBucket: 'memocards-37431.firebasestorage.app',
    measurementId: 'G-1BQJEE65XB',
  );
}
